version: '2.0'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    environment:
      - KAFKA_HEAP_OPTS=-Xmx16M -Xms16M
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_HEAP_OPTS=-Xmx32M -Xms32M
      - KAFKA_CREATE_TOPICS=order:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper      
    volumes:
      - ./kafkaconfig:/opt/kafka/config # you can change volumes
# kafka image information : https://github.com/wurstmeister/kafka-docker
# kafka 2.1.0 available java 11 https://kafka.apache.org/downloads
