version: "2.0" 
services:
  db1:
    image: mysql:5.7
    restart: always
    command: --lower_case_table_names=1
    container_name: read
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=read
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # you can change volumes      
  db2:
   image: mysql:5.7
   restart: always
   command: --lower_case_table_names=1
   container_name: event
   ports:
     - "3308:3306"
   environment:
     - MYSQL_DATABASE=event
     - MYSQL_ROOT_PASSWORD=1234
     - TZ=Asia/Seoul
   command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock # you can change volumes   