version: "2.0" 
services: 
  db:
    image: mysql:5.7
    restart: always
    command: --lower_case_table_names=1
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # you can change volumes